const axios = require("axios");
const http = require("http");

const options = {
  host: 'api.sgcp.sp.gov.br',
  headers: { 'Content-Type': 'application/json' },
  httpAgent: new http.Agent({ keepAlive: true }),
};

const cities = [
  { id: 8853, cityName: "Adamantina" },
  { id: 8854, cityName: "Adolfo" },
  { id: 8857, cityName: "Aguaí" },
  { id: 8858, cityName: "Águas da Prata" },
  { id: 8859, cityName: "Águas de Lindóia" },
  { id: 8860, cityName: "Águas de Santa Bárbara" },
  { id: 8861, cityName: "Águas de São Pedro" },
  { id: 8862, cityName: "Agudos" },
  { id: 8865, cityName: "Alambari" },
  { id: 8870, cityName: "Alfredo Marcondes" },
  { id: 8871, cityName: "Altair" },
  { id: 8872, cityName: "Altinópolis" },
  { id: 8873, cityName: "Alto Alegre" },
  { id: 8875, cityName: "Alumínio" },
  { id: 8876, cityName: "Álvares Florence" },
  { id: 8877, cityName: "Álvares Machado" },
  { id: 8878, cityName: "Álvaro de Carvalho" },
  { id: 8879, cityName: "Alvinlândia" },
  { id: 8883, cityName: "Americana" },
  { id: 8884, cityName: "Américo Brasiliense" },
  { id: 8885, cityName: "Américo de Campos" },
  { id: 8886, cityName: "Amparo" },
  { id: 8888, cityName: "Analândia" },
  { id: 8891, cityName: "Andradina" },
  { id: 8892, cityName: "Angatuba" },
  { id: 8893, cityName: "Anhembi" },
  { id: 8894, cityName: "Anhumas" },
  { id: 8896, cityName: "Aparecida" },
  { id: 8897, cityName: "Aparecida D'Oeste" },
  { id: 8901, cityName: "Apiaí" },
  { id: 8906, cityName: "Araçariguama" },
  { id: 8907, cityName: "Araçatuba" },
  { id: 8908, cityName: "Araçoiaba da Serra" },
  { id: 8909, cityName: "Aramina" },
  { id: 8910, cityName: "Arandu" },
  { id: 8911, cityName: "Arapeí" },
  { id: 8912, cityName: "Araraquara" },
  { id: 8913, cityName: "Araras" },
  { id: 8916, cityName: "Arco-Íris" },
  { id: 8917, cityName: "Arealva" },
  { id: 8918, cityName: "Areias" },
  { id: 8919, cityName: "Areiópolis" },
  { id: 8920, cityName: "Ariranha" },
  { id: 8923, cityName: "Artur Nogueira" },
  { id: 8924, cityName: "Arujá" },
  { id: 8925, cityName: "Aspásia" },
  { id: 8926, cityName: "Assis" },
  { id: 8928, cityName: "Atibaia" },
  { id: 8930, cityName: "Auriflama" },
  { id: 8931, cityName: "Avaí" },
  { id: 8932, cityName: "Avanhandava" },
  { id: 8933, cityName: "Avaré" },
  { id: 8937, cityName: "Bady Bassitt" },
  { id: 8940, cityName: "Balbinos" },
  { id: 8941, cityName: "Bálsamo" },
  { id: 8942, cityName: "Bananal" },
  { id: 8945, cityName: "Barão de Antonina" },
  { id: 8947, cityName: "Barbosa" },
  { id: 8948, cityName: "Bariri" },
  { id: 8949, cityName: "Barra Bonita" },
  { id: 8950, cityName: "Barra do Chapéu" },
  { id: 8951, cityName: "Barra do Turvo" },
  { id: 8954, cityName: "Barretos" },
  { id: 8955, cityName: "Barrinha" },
  { id: 8956, cityName: "Barueri" },
  { id: 8957, cityName: "Bastos" },
  { id: 8958, cityName: "Batatais" },
  { id: 8961, cityName: "Bauru" },
  { id: 8962, cityName: "Bebedouro" },
  { id: 8965, cityName: "Bento de Abreu" },
  { id: 8966, cityName: "Bernardino de Campos" },
  { id: 8967, cityName: "Bertioga" },
  { id: 8968, cityName: "Bilac" },
  { id: 8969, cityName: "Birigüi" },
  { id: 8970, cityName: "Biritiba-Mirim" },
  { id: 8972, cityName: "Boa Esperança do Sul" },
  { id: 8975, cityName: "Bocaina" },
  { id: 8976, cityName: "Bofete" },
  { id: 8977, cityName: "Boituva" },
  { id: 8979, cityName: "Bom Jesus dos Perdões" },
  { id: 8981, cityName: "Bom Sucesso de Itararé" },
  { id: 8983, cityName: "Borá" },
  { id: 8984, cityName: "Boracéia" },
  { id: 8985, cityName: "Borborema" },
  { id: 8986, cityName: "Borebi" },
  { id: 8989, cityName: "Botucatu" },
  { id: 8992, cityName: "Bragança Paulista" },
  { id: 8995, cityName: "Braúna" },
  { id: 8996, cityName: "Brejo Alegre" },
  { id: 8997, cityName: "Brodowski" },
  { id: 8998, cityName: "Brotas" },
  { id: 9000, cityName: "Buri" },
  { id: 9001, cityName: "Buritama" },
  { id: 9002, cityName: "Buritizal" },
  { id: 9003, cityName: "Cabrália Paulista" },
  { id: 9004, cityName: "Cabreúva" },
  { id: 9005, cityName: "Caçapava" },
  { id: 9007, cityName: "Cachoeira Paulista" },
  { id: 9008, cityName: "Caconde" },
  { id: 9009, cityName: "Cafelândia" },
  { id: 9011, cityName: "Caiabu" },
  { id: 9013, cityName: "Caieiras" },
  { id: 9014, cityName: "Caiuá" },
  { id: 9015, cityName: "Cajamar" },
  { id: 9016, cityName: "Cajati" },
  { id: 9017, cityName: "Cajobi" },
  { id: 9018, cityName: "Cajuru" },
  { id: 9023, cityName: "Campina do Monte Alegre" },
  { id: 9025, cityName: "Campinas" },
  { id: 9026, cityName: "Campo Limpo Paulista" },
  { id: 9028, cityName: "Campos do Jordão" },
  { id: 9029, cityName: "Campos Novos Paulista" },
  { id: 9030, cityName: "Cananéia" },
  { id: 9031, cityName: "Canas" },
  { id: 9033, cityName: "Cândido Mota" },
  { id: 9034, cityName: "Cândido Rodrigues" },
  { id: 9036, cityName: "Canitar" },
  { id: 9037, cityName: "Capão Bonito" },
  { id: 9038, cityName: "Capela do Alto" },
  { id: 9039, cityName: "Capivari" },
  { id: 9043, cityName: "Caraguatatuba" },
  { id: 9044, cityName: "Carapicuíba" },
  { id: 9046, cityName: "Cardoso" },
  { id: 9049, cityName: "Casa Branca" },
  { id: 9050, cityName: "Cássia dos Coqueiros" },
  { id: 9051, cityName: "Castilho" },
  { id: 9052, cityName: "Catanduva" },
  { id: 9053, cityName: "Catiguá" },
  { id: 9056, cityName: "Cedral" },
  { id: 9057, cityName: "Cerqueira César" },
  { id: 9058, cityName: "Cerquilho" },
  { id: 9059, cityName: "Cesário Lange" },
  { id: 9061, cityName: "Charqueada" },
  { id: 9062, cityName: "Chavantes" },
  { id: 9065, cityName: "Clementina" },
  { id: 9067, cityName: "Colina" },
  { id: 9068, cityName: "Colômbia" },
  { id: 9070, cityName: "Conchal" },
  { id: 9071, cityName: "Conchas" },
  { id: 9072, cityName: "Cordeirópolis" },
  { id: 9073, cityName: "Coroados" },
  { id: 9075, cityName: "Coronel Macedo" },
  { id: 9078, cityName: "Corumbataí" },
  { id: 9079, cityName: "Cosmópolis" },
  { id: 9080, cityName: "Cosmorama" },
  { id: 9082, cityName: "Cotia" },
  { id: 9083, cityName: "Cravinhos" },
  { id: 9084, cityName: "Cristais Paulista" },
  { id: 9086, cityName: "Cruzália" },
  { id: 9087, cityName: "Cruzeiro" },
  { id: 9088, cityName: "Cubatão" },
  { id: 9090, cityName: "Cunha" },
  { id: 9093, cityName: "Descalvado" },
  { id: 9094, cityName: "Diadema" },
  { id: 9095, cityName: "Dirce Reis" },
  { id: 9097, cityName: "Divinolândia" },
  { id: 9098, cityName: "Dobrada" },
  { id: 9099, cityName: "Dois Córregos" },
  { id: 9100, cityName: "Dolcinópolis" },
  { id: 9102, cityName: "Dourado" },
  { id: 9103, cityName: "Dracena" },
  { id: 9104, cityName: "Duartina" },
  { id: 9105, cityName: "Dumont" },
  { id: 9107, cityName: "Echaporã" },
  { id: 9108, cityName: "Eldorado" },
  { id: 9110, cityName: "Elias Fausto" },
  { id: 9111, cityName: "Elisiário" },
  { id: 9112, cityName: "Embaúba" },
  { id: 9113, cityName: "Embu das Artes" },
  { id: 9114, cityName: "Embu-Guaçu" },
  { id: 9115, cityName: "Emilianópolis" },
  { id: 9118, cityName: "Engenheiro Coelho" },
  { id: 9124, cityName: "Espírito Santo do Pinhal" },
  { id: 9125, cityName: "Espírito Santo do Turvo" },
  { id: 9126, cityName: "Estiva Gerbi" },
  { id: 9128, cityName: "Estrela do Norte" },
  { id: 9127, cityName: "Estrela D'Oeste" },
  { id: 9129, cityName: "Euclides da Cunha Paulista" },
  { id: 9131, cityName: "Fartura" },
  { id: 9135, cityName: "Fernando Prestes" },
  { id: 9136, cityName: "Fernandópolis" },
  { id: 9137, cityName: "Fernão" },
  { id: 9138, cityName: "Ferraz de Vasconcelos" },
  { id: 9139, cityName: "Flora Rica" },
  { id: 9140, cityName: "Floreal" },
  { id: 9142, cityName: "Flórida Paulista" },
  { id: 9143, cityName: "Florínia" },
  { id: 9144, cityName: "Franca" },
  { id: 9145, cityName: "Francisco Morato" },
  { id: 9146, cityName: "Franco da Rocha" },
  { id: 9148, cityName: "Gabriel Monteiro" },
  { id: 9149, cityName: "Gália" },
  { id: 9150, cityName: "Garça" },
  { id: 9152, cityName: "Gastão Vidigal" },
  { id: 9153, cityName: "Gavião Peixoto" },
  { id: 9154, cityName: "General Salgado" },
  { id: 9155, cityName: "Getulina" },
  { id: 9156, cityName: "Glicério" },
  { id: 9160, cityName: "Guaiçara" },
  { id: 9161, cityName: "Guaimbê" },
  { id: 9162, cityName: "Guaíra" },
  { id: 9164, cityName: "Guapiaçu" },
  { id: 9165, cityName: "Guapiara" },
  { id: 9167, cityName: "Guará" },
  { id: 9168, cityName: "Guaraçaí" },
  { id: 9169, cityName: "Guaraci" },
  { id: 9171, cityName: "Guarani D'Oeste" },
  { id: 9172, cityName: "Guarantã" },
  { id: 9175, cityName: "Guararapes" },
  { id: 9176, cityName: "Guararema" },
  { id: 9177, cityName: "Guaratinguetá" },
  { id: 9178, cityName: "Guareí" },
  { id: 9179, cityName: "Guariba" },
  { id: 9182, cityName: "Guarujá" },
  { id: 9183, cityName: "Guarulhos" },
  { id: 9184, cityName: "Guatapará" },
  { id: 9185, cityName: "Guzolândia" },
  { id: 9186, cityName: "Herculândia" },
  { id: 9187, cityName: "Holambra" },
  { id: 9189, cityName: "Hortolândia" },
  { id: 9190, cityName: "Iacanga" },
  { id: 9191, cityName: "Iacri" },
  { id: 9192, cityName: "Iaras" },
  { id: 9193, cityName: "Ibaté" },
  { id: 9195, cityName: "Ibirá" },
  { id: 9196, cityName: "Ibirarema" },
  { id: 9197, cityName: "Ibitinga" },
  { id: 9201, cityName: "Ibiúna" },
  { id: 9202, cityName: "Icém" },
  { id: 9204, cityName: "Iepê" },
  { id: 9206, cityName: "Igaraçu do Tietê" },
  { id: 9208, cityName: "Igarapava" },
  { id: 9209, cityName: "Igaratá" },
  { id: 9210, cityName: "Iguape" },
  { id: 9211, cityName: "Ilha Comprida" },
  { id: 9213, cityName: "Ilha Solteira" },
  { id: 9214, cityName: "Ilhabela" },
  { id: 9216, cityName: "Indaiatuba" },
  { id: 9217, cityName: "Indiana" },
  { id: 9218, cityName: "Indiaporã" },
  { id: 9220, cityName: "Inúbia Paulista" },
  { id: 9221, cityName: "Ipaussu" },
  { id: 9222, cityName: "Iperó" },
  { id: 9223, cityName: "Ipeúna" },
  { id: 9224, cityName: "Ipiguá" },
  { id: 9225, cityName: "Iporanga" },
  { id: 9226, cityName: "Ipuã" },
  { id: 9227, cityName: "Iracemápolis" },
  { id: 9229, cityName: "Irapuã" },
  { id: 9230, cityName: "Irapuru" },
  { id: 9231, cityName: "Itaberá" },
  { id: 9233, cityName: "Itaí" },
  { id: 9235, cityName: "Itajobi" },
  { id: 9236, cityName: "Itaju" },
  { id: 9237, cityName: "Itanhaém" },
  { id: 9238, cityName: "Itaóca" },
  { id: 9239, cityName: "Itapecerica da Serra" },
  { id: 9240, cityName: "Itapetininga" },
  { id: 9242, cityName: "Itapeva" },
  { id: 9243, cityName: "Itapevi" },
  { id: 9244, cityName: "Itapira" },
  { id: 9245, cityName: "Itapirapuã Paulista" },
  { id: 9246, cityName: "Itápolis" },
  { id: 9247, cityName: "Itaporanga" },
  { id: 9248, cityName: "Itapuí" },
  { id: 9249, cityName: "Itapura" },
  { id: 9250, cityName: "Itaquaquecetuba" },
  { id: 9252, cityName: "Itararé" },
  { id: 9253, cityName: "Itariri" },
  { id: 9254, cityName: "Itatiba" },
  { id: 9255, cityName: "Itatinga" },
  { id: 9256, cityName: "Itirapina" },
  { id: 9257, cityName: "Itirapuã" },
  { id: 9258, cityName: "Itobi" },
  { id: 9260, cityName: "Itu" },
  { id: 9261, cityName: "Itupeva" },
  { id: 9262, cityName: "Ituverava" },
  { id: 9264, cityName: "Jaborandi" },
  { id: 9265, cityName: "Jaboticabal" },
  { id: 9267, cityName: "Jacareí" },
  { id: 9268, cityName: "Jaci" },
  { id: 9271, cityName: "Jacupiranga" },
  { id: 9273, cityName: "Jaguariúna" },
  { id: 9274, cityName: "Jales" },
  { id: 9276, cityName: "Jambeiro" },
  { id: 9277, cityName: "Jandira" },
  { id: 9282, cityName: "Jardinópolis" },
  { id: 9283, cityName: "Jarinu" },
  { id: 9285, cityName: "Jaú" },
  { id: 9286, cityName: "Jeriquara" },
  { id: 9287, cityName: "Joanópolis" },
  { id: 9288, cityName: "João Ramalho" },
  { id: 9291, cityName: "José Bonifácio" },
  { id: 9293, cityName: "Júlio Mesquita" },
  { id: 9294, cityName: "Jumirim" },
  { id: 9295, cityName: "Jundiaí" },
  { id: 9298, cityName: "Junqueirópolis" },
  { id: 9299, cityName: "Juquiá" },
  { id: 9301, cityName: "Juquitiba" },
  { id: 9309, cityName: "Lagoinha" },
  { id: 9310, cityName: "Laranjal Paulista" },
  { id: 9313, cityName: "Lavínia" },
  { id: 9314, cityName: "Lavrinhas" },
  { id: 9315, cityName: "Leme" },
  { id: 9316, cityName: "Lençóis Paulista" },
  { id: 9317, cityName: "Limeira" },
  { id: 9318, cityName: "Lindóia" },
  { id: 9319, cityName: "Lins" },
  { id: 9321, cityName: "Lorena" },
  { id: 9322, cityName: "Lourdes" },
  { id: 9323, cityName: "Louveira" },
  { id: 9324, cityName: "Lucélia" },
  { id: 9325, cityName: "Lucianópolis" },
  { id: 9326, cityName: "Luís Antônio" },
  { id: 9327, cityName: "Luiziânia" },
  { id: 9328, cityName: "Lupércio" },
  { id: 9330, cityName: "Lutécia" },
  { id: 9331, cityName: "Macatuba" },
  { id: 9332, cityName: "Macaubal" },
  { id: 9333, cityName: "Macedônia" },
  { id: 9335, cityName: "Mágda" },
  { id: 9337, cityName: "Mairinque" },
  { id: 9338, cityName: "Mairiporã" },
  { id: 9340, cityName: "Manduri" },
  { id: 9342, cityName: "Marabá Paulista" },
  { id: 9343, cityName: "Maracaí" },
  { id: 9344, cityName: "Marapoama" },
  { id: 9347, cityName: "Mariápolis" },
  { id: 9348, cityName: "Marília" },
  { id: 9349, cityName: "Marinópolis" },
  { id: 9353, cityName: "Martinópolis" },
  { id: 9354, cityName: "Matão" },
  { id: 9355, cityName: "Mauá" },
  { id: 9356, cityName: "Mendonça" },
  { id: 9357, cityName: "Meridiano" },
  { id: 9358, cityName: "Mesópolis" },
  { id: 9359, cityName: "Miguelópolis" },
  { id: 9360, cityName: "Mineiros do Tietê" },
  { id: 9361, cityName: "Mira Estrela" },
  { id: 9362, cityName: "Miracatu" },
  { id: 9364, cityName: "Mirandópolis" },
  { id: 9365, cityName: "Mirante do Paranapanema" },
  { id: 9366, cityName: "Mirassol" },
  { id: 9367, cityName: "Mirassolândia" },
  { id: 9368, cityName: "Mococa" },
  { id: 9369, cityName: "Mogi das Cruzes" },
  { id: 9370, cityName: "Mogi Guaçu" },
  { id: 9371, cityName: "Mogi Mirim" },
  { id: 9372, cityName: "Mombuca" },
  { id: 9373, cityName: "Monções" },
  { id: 9374, cityName: "Mongaguá" },
  { id: 9376, cityName: "Monte Alegre do Sul" },
  { id: 9377, cityName: "Monte Alto" },
  { id: 9378, cityName: "Monte Aprazível" },
  { id: 9379, cityName: "Monte Azul Paulista" },
  { id: 9381, cityName: "Monte Castelo" },
  { id: 9382, cityName: "Monte Mor" },
  { id: 9384, cityName: "Monteiro Lobato" },
  { id: 9386, cityName: "Morro Agudo" },
  { id: 9388, cityName: "Morungaba" },
  { id: 9390, cityName: "Motuca" },
  { id: 9392, cityName: "Murutinga do Sul" },
  { id: 9393, cityName: "Nantes" },
  { id: 9394, cityName: "Narandiba" },
  { id: 9395, cityName: "Natividade da Serra" },
  { id: 9396, cityName: "Nazaré Paulista" },
  { id: 9397, cityName: "Neves Paulista" },
  { id: 9398, cityName: "Nhandeara" },
  { id: 9399, cityName: "Nipoã" },
  { id: 9403, cityName: "Nova Aliança" },
  { id: 9406, cityName: "Nova Campina" },
  { id: 9407, cityName: "Nova Canaã Paulista" },
  { id: 9408, cityName: "Nova Castilho" },
  { id: 9409, cityName: "Nova Europa" },
  { id: 9410, cityName: "Nova Granada" },
  { id: 9411, cityName: "Nova Guataporanga" },
  { id: 9412, cityName: "Nova Independência" },
  { id: 9414, cityName: "Nova Luzitânia" },
  { id: 9415, cityName: "Nova Odessa" },
  { id: 9418, cityName: "Novais" },
  { id: 9420, cityName: "Novo Horizonte" },
  { id: 9421, cityName: "Nuporanga" },
  { id: 9423, cityName: "Ocauçu" },
  { id: 9424, cityName: "Óleo" },
  { id: 9425, cityName: "Olímpia" },
  { id: 9428, cityName: "Onda Verde" },
  { id: 9429, cityName: "Oriente" },
  { id: 9430, cityName: "Orindiúva" },
  { id: 9431, cityName: "Orlândia" },
  { id: 9432, cityName: "Osasco" },
  { id: 9433, cityName: "Oscar Bressane" },
  { id: 9434, cityName: "Osvaldo Cruz" },
  { id: 9435, cityName: "Ourinhos" },
  { id: 9437, cityName: "Ouro Verde" },
  { id: 9438, cityName: "Ouroeste" },
  { id: 9439, cityName: "Pacaembu" },
  { id: 9441, cityName: "Palestina" },
  { id: 9442, cityName: "Palmares Paulista" },
  { id: 9443, cityName: "Palmeira D'Oeste" },
  { id: 9445, cityName: "Palmital" },
  { id: 9446, cityName: "Panorama" },
  { id: 9447, cityName: "Paraguaçu Paulista" },
  { id: 9448, cityName: "Paraibuna" },
  { id: 9449, cityName: "Paraíso" },
  { id: 9452, cityName: "Paranapanema" },
  { id: 9454, cityName: "Paranapuã" },
  { id: 9455, cityName: "Parapuã" },
  { id: 9456, cityName: "Pardinho" },
  { id: 9457, cityName: "Pariquera-Açu" },
  { id: 9458, cityName: "Parisi" },
  { id: 9462, cityName: "Patrocínio Paulista" },
  { id: 9463, cityName: "Paulicéia" },
  { id: 9464, cityName: "Paulínia" },
  { id: 9465, cityName: "Paulistânia" },
  { id: 9466, cityName: "Paulo de Faria" },
  { id: 9468, cityName: "Pederneiras" },
  { id: 9469, cityName: "Pedra Bela" },
  { id: 9471, cityName: "Pedranópolis" },
  { id: 9472, cityName: "Pedregulho" },
  { id: 9473, cityName: "Pedreira" },
  { id: 9474, cityName: "Pedrinhas Paulista" },
  { id: 9476, cityName: "Pedro de Toledo" },
  { id: 9477, cityName: "Penápolis" },
  { id: 9478, cityName: "Pereira Barreto" },
  { id: 9479, cityName: "Pereiras" },
  { id: 9480, cityName: "Peruíbe" },
  { id: 9481, cityName: "Piacatu" },
  { id: 9483, cityName: "Piedade" },
  { id: 9484, cityName: "Pilar do Sul" },
  { id: 9485, cityName: "Pindamonhangaba" },
  { id: 9486, cityName: "Pindorama" },
  { id: 9487, cityName: "Pinhalzinho" },
  { id: 9490, cityName: "Piquerobi" },
  { id: 9491, cityName: "Piquete" },
  { id: 9492, cityName: "Piracaia" },
  { id: 9493, cityName: "Piracicaba" },
  { id: 9494, cityName: "Piraju" },
  { id: 9495, cityName: "Pirajuí" },
  { id: 9497, cityName: "Pirangi" },
  { id: 9499, cityName: "Pirapora do Bom Jesus" },
  { id: 9500, cityName: "Pirapozinho" },
  { id: 9501, cityName: "Pirassununga" },
  { id: 9502, cityName: "Piratininga" },
  { id: 9503, cityName: "Pitangueiras" },
  { id: 9504, cityName: "Planalto" },
  { id: 9507, cityName: "Platina" },
  { id: 9508, cityName: "Poá" },
  { id: 9509, cityName: "Poloni" },
  { id: 9511, cityName: "Pompéia" },
  { id: 9512, cityName: "Pongaí" },
  { id: 9513, cityName: "Pontal" },
  { id: 9514, cityName: "Pontalinda" },
  { id: 9515, cityName: "Pontes Gestal" },
  { id: 9516, cityName: "Populina" },
  { id: 9517, cityName: "Porangaba" },
  { id: 9518, cityName: "Porto Feliz" },
  { id: 9519, cityName: "Porto Ferreira" },
  { id: 9521, cityName: "Potim" },
  { id: 9522, cityName: "Potirendaba" },
  { id: 9524, cityName: "Pracinha" },
  { id: 9526, cityName: "Pradópolis" },
  { id: 9527, cityName: "Praia Grande" },
  { id: 9528, cityName: "Pratânia" },
  { id: 9529, cityName: "Presidente Alves" },
  { id: 9530, cityName: "Presidente Bernardes" },
  { id: 9531, cityName: "Presidente Epitácio" },
  { id: 9532, cityName: "Presidente Prudente" },
  { id: 9533, cityName: "Presidente Venceslau" },
  { id: 9535, cityName: "Promissão" },
  { id: 9537, cityName: "Quadra" },
  { id: 9538, cityName: "Quatá" },
  { id: 9539, cityName: "Queiroz" },
  { id: 9540, cityName: "Queluz" },
  { id: 9541, cityName: "Quintana" },
  { id: 9543, cityName: "Rafard" },
  { id: 9544, cityName: "Rancharia" },
  { id: 9546, cityName: "Redenção da Serra" },
  { id: 9547, cityName: "Regente Feijó" },
  { id: 9548, cityName: "Reginópolis" },
  { id: 9549, cityName: "Registro" },
  { id: 9550, cityName: "Restinga" },
  { id: 9552, cityName: "Ribeira" },
  { id: 9553, cityName: "Ribeirão Bonito" },
  { id: 9554, cityName: "Ribeirão Branco" },
  { id: 9555, cityName: "Ribeirão Corrente" },
  { id: 9556, cityName: "Ribeirão do Sul" },
  { id: 9557, cityName: "Ribeirão dos Índios" },
  { id: 9558, cityName: "Ribeirão Grande" },
  { id: 9559, cityName: "Ribeirão Pires" },
  { id: 9560, cityName: "Ribeirão Preto" },
  { id: 9563, cityName: "Rifaina" },
  { id: 9564, cityName: "Rincão" },
  { id: 9565, cityName: "Rinópolis" },
  { id: 9566, cityName: "Rio Claro" },
  { id: 9567, cityName: "Rio das Pedras" },
  { id: 9568, cityName: "Rio Grande da Serra" },
  { id: 9569, cityName: "Riolândia" },
  { id: 9570, cityName: "Riversul" },
  { id: 9573, cityName: "Rosana" },
  { id: 9574, cityName: "Roseira" },
  { id: 9575, cityName: "Rubiácea" },
  { id: 9577, cityName: "Rubinéia" },
  { id: 9580, cityName: "Sabino" },
  { id: 9581, cityName: "Sagres" },
  { id: 9582, cityName: "Sales" },
  { id: 9583, cityName: "Sales Oliveira" },
  { id: 9584, cityName: "Salesópolis" },
  { id: 9585, cityName: "Salmourão" },
  { id: 9586, cityName: "Saltinho" },
  { id: 9587, cityName: "Salto" },
  { id: 9588, cityName: "Salto de Pirapora" },
  { id: 9590, cityName: "Salto Grande" },
  { id: 9591, cityName: "Sandovalina" },
  { id: 9592, cityName: "Santa Adélia" },
  { id: 9593, cityName: "Santa Albertina" },
  { id: 9595, cityName: "Santa Bárbara D'Oeste" },
  { id: 9596, cityName: "Santa Branca" },
  { id: 9597, cityName: "Santa Clara D'Oeste" },
  { id: 9598, cityName: "Santa Cruz da Conceição" },
  { id: 9599, cityName: "Santa Cruz da Esperança" },
  { id: 9601, cityName: "Santa Cruz das Palmeiras" },
  { id: 9602, cityName: "Santa Cruz do Rio Pardo" },
  { id: 9604, cityName: "Santa Ernestina" },
  { id: 9606, cityName: "Santa Fé do Sul" },
  { id: 9607, cityName: "Santa Gertrudes" },
  { id: 9608, cityName: "Santa Isabel" },
  { id: 9610, cityName: "Santa Lúcia" },
  { id: 9612, cityName: "Santa Maria da Serra" },
  { id: 9614, cityName: "Santa Mercedes" },
  { id: 9616, cityName: "Santa Rita do Passa Quatro" },
  { id: 9615, cityName: "Santa Rita D'Oeste" },
  { id: 9618, cityName: "Santa Rosa de Viterbo" },
  { id: 9619, cityName: "Santa Salete" },
  { id: 9621, cityName: "Santana da Ponte Pensa" },
  { id: 9622, cityName: "Santana de Parnaíba" },
  { id: 9624, cityName: "Santo Anastácio" },
  { id: 9625, cityName: "Santo André" },
  { id: 9626, cityName: "Santo Antônio da Alegria" },
  { id: 9628, cityName: "Santo Antônio de Posse" },
  { id: 9629, cityName: "Santo Antônio do Aracanguá" },
  { id: 9630, cityName: "Santo Antônio do Jardim" },
  { id: 9632, cityName: "Santo Antônio do Pinhal" },
  { id: 9634, cityName: "Santo Expedito" },
  { id: 9635, cityName: "Santópolis do Aguapeí" },
  { id: 9636, cityName: "Santos" },
  { id: 9639, cityName: "São Bento do Sapucaí" },
  { id: 9640, cityName: "São Bernardo do Campo" },
  { id: 9642, cityName: "São Caetano do Sul" },
  { id: 9643, cityName: "São Carlos" },
  { id: 9644, cityName: "São Francisco" },
  { id: 9647, cityName: "São João da Boa Vista" },
  { id: 9648, cityName: "São João das Duas Pontes" },
  { id: 9649, cityName: "São João de Iracema" },
  { id: 9652, cityName: "São João do Pau D'Alho" },
  { id: 9654, cityName: "São Joaquim da Barra" },
  { id: 9655, cityName: "São José da Bela Vista" },
  { id: 9657, cityName: "São José do Barreiro" },
  { id: 9658, cityName: "São José do Rio Pardo" },
  { id: 9659, cityName: "São José do Rio Preto" },
  { id: 9660, cityName: "São José dos Campos" },
  { id: 9661, cityName: "São Lourenço da Serra" },
  { id: 9663, cityName: "São Luiz do Paraitinga" },
  { id: 9665, cityName: "São Manuel" },
  { id: 9667, cityName: "São Miguel Arcanjo" },
  { id: 9668, cityName: "São Paulo" },
  { id: 9669, cityName: "São Pedro" },
  { id: 9670, cityName: "São Pedro do Turvo" },
  { id: 9671, cityName: "São Roque" },
  { id: 9673, cityName: "São Sebastião" },
  { id: 9674, cityName: "São Sebastião da Grama" },
  { id: 9677, cityName: "São Simão" },
  { id: 9678, cityName: "São Vicente" },
  { id: 9680, cityName: "Sarapuí" },
  { id: 9681, cityName: "Sarutaiá" },
  { id: 9682, cityName: "Sebastianópolis do Sul" },
  { id: 9683, cityName: "Serra Azul" },
  { id: 9684, cityName: "Serra Negra" },
  { id: 9685, cityName: "Serrana" },
  { id: 9686, cityName: "Sertãozinho" },
  { id: 9687, cityName: "Sete Barras" },
  { id: 9688, cityName: "Severínia" },
  { id: 9690, cityName: "Silveiras" },
  { id: 9693, cityName: "Socorro" },
  { id: 9696, cityName: "Sorocaba" },
  { id: 9698, cityName: "Sud Mennucci" },
  { id: 9700, cityName: "Sumaré" },
  { id: 9702, cityName: "Suzanápolis" },
  { id: 9703, cityName: "Suzano" },
  { id: 9705, cityName: "Tabapuã" },
  { id: 9706, cityName: "Tabatinga" },
  { id: 9707, cityName: "Taboão da Serra" },
  { id: 9708, cityName: "Taciba" },
  { id: 9709, cityName: "Taguaí" },
  { id: 9710, cityName: "Taiaçu" },
  { id: 9712, cityName: "Taiúva" },
  { id: 9714, cityName: "Tambaú" },
  { id: 9715, cityName: "Tanabi" },
  { id: 9717, cityName: "Tapiraí" },
  { id: 9718, cityName: "Tapiratiba" },
  { id: 9719, cityName: "Taquaral" },
  { id: 9720, cityName: "Taquaritinga" },
  { id: 9721, cityName: "Taquarituba" },
  { id: 9722, cityName: "Taquarivaí" },
  { id: 9723, cityName: "Tarabai" },
  { id: 9724, cityName: "Tarumã" },
  { id: 9725, cityName: "Tatuí" },
  { id: 9726, cityName: "Taubaté" },
  { id: 9728, cityName: "Tejupá" },
  { id: 9729, cityName: "Teodoro Sampaio" },
  { id: 9732, cityName: "Terra Roxa" },
  { id: 9735, cityName: "Tietê" },
  { id: 9736, cityName: "Timburi" },
  { id: 9738, cityName: "Torre de Pedra" },
  { id: 9739, cityName: "Torrinha" },
  { id: 9740, cityName: "Trabiju" },
  { id: 9741, cityName: "Tremembé" },
  { id: 9743, cityName: "Três Fronteiras" },
  { id: 9746, cityName: "Tuiuti" },
  { id: 9748, cityName: "Tupã" },
  { id: 9750, cityName: "Tupi Paulista" },
  { id: 9752, cityName: "Turiúba" },
  { id: 9753, cityName: "Turmalina" },
  { id: 9755, cityName: "Ubarana" },
  { id: 9756, cityName: "Ubatuba" },
  { id: 9757, cityName: "Ubirajara" },
  { id: 9758, cityName: "Uchoa" },
  { id: 9759, cityName: "União Paulista" },
  { id: 9761, cityName: "Urânia" },
  { id: 9762, cityName: "Uru" },
  { id: 9763, cityName: "Urupês" },
  { id: 9767, cityName: "Valentim Gentil" },
  { id: 9768, cityName: "Valinhos" },
  { id: 9769, cityName: "Valparaíso" },
  { id: 9771, cityName: "Vargem" },
  { id: 9772, cityName: "Vargem Grande do Sul" },
  { id: 9773, cityName: "Vargem Grande Paulista" },
  { id: 9775, cityName: "Várzea Paulista" },
  { id: 9777, cityName: "Vera Cruz" },
  { id: 9783, cityName: "Vinhedo" },
  { id: 9784, cityName: "Viradouro" },
  { id: 9785, cityName: "Vista Alegre do Alto" },
  { id: 9786, cityName: "Vitória Brasil" },
  { id: 9788, cityName: "Votorantim" },
  { id: 9789, cityName: "Votuporanga" },
  { id: 9790, cityName: "Zacarias" },
];

console.log(`\n\n[SGCP API - Via Rápida Cursos]`);
console.log(`[Desenvolvido por @ryahpalma]`);
console.log(`\nLembre-se de verificar o e-mail toda terça-feira`);
console.log(`\nBuscando cursos disponíveis...`);

var validCities = cities.map(function (item) {
  return {
    idCity: item.id,
    cityName: item.cityName
  }
});

validCities.forEach(function (item) {
  axios
    .get(
      'http://api.sgcp.sp.gov.br/api/v1/cursoQualificacao/turmasAbertas?idModalidade=1&idMunicipio=' + item.idCity, options
    )
    .then((response) => {
      for (key in response.data) {
        if (response.data != null && key == 0) {

          console.log(`\nBusca feita em ${item.cityName}`);

          var validCourses = response.data.map(function (item) {
            return {
              courseName: item.nome,
              workLoad: item.cargaHoraria,
              Avaiable: item.imagem.hasInscricoesAbertas,
            }
          });

          validCourses.forEach(function (item) {
            if (!item.Avaiable == false) {
              console.log(`Curso: [${item.courseName}] com carga horária de ${item.workLoad} horas.}`);
            }
            else {
              console.log(`Não foi encontrado inscrições abertas...`);
            }
          });
        }
      }
    })
    .catch((error) => {
      return;
    });
});
